### ISSUE TITLE
No extra Music Sheets

### ISSUE THREAD

**Issue by MageoMage** [DeamonHunter/ArchipelagoMuseDash#20]
Was Playing in a multiworld yesterday, settings were 8 Sheets needed to win, 12 in total. At the end there were only 8 present in the world (sadly don't have access to the spoiler log of the world rn)

**Comment by DeamonHunter** [comment]
As a first measure, can you upload your yaml here? (Also whether or not your using the 0.3.8 version for the dev version.)

Otherwise yeah the full spoiler would help.

**Comment by MageoMage** [comment]
Sadly I wasn't generating and by now it also has been a while as that I would remember much anymore :/
but here the YAML
[MusicMage.txt](https://github.com/DeamonHunter/ArchipelagoMuseDash/files/10973386/MusicMage.txt)

**Comment by DeamonHunter** [comment]
You've accidentally set the two values the wrong way round:
```yaml
  music_sheet_count:
    # The amount of Music Sheets spread around this seed. Music Sheets are required to unlock the final song.
    #
    # You can define additional values between the minimum and maximum values.
    # Minimum value is 1
    # Maximum value is 12
    8: 50

  music_sheet_win_count:
    # The number of Music Sheets needed to unlock the winning song.
    #
    # You can define additional values between the minimum and maximum values.
    # Minimum value is 1
    # Maximum value is 12
    12: 50
```

When this happens, the randomiser clamps will clamp the number of sheets to win, to the number of sheets spawned.

I will be experimenting with percentage based amounts in a future world. (When traps get programmed and added.)
